version: '3'
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    tty: true
    environment:
      - TZ="Asia/Tokyo"

#  db:
#    image: mysql:5.7
#    volumes:
#      - ./mysql/conf:/etc/mysql/conf.d
#      - ./mysql/data:/var/lib/mysql
#    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-time-zone=Asia/Tokyo
#    ports:
#      - 5306:3306
#    environment:
#      - MYSQL_USER=hubble
#      - MYSQL_PASSWORD=sample
#      - MYSQL_DATABASE=sample
#      - MYSQL_ROOT_PASSWORD=sample
#      - TZ="Asia/Tokyo"
#    networks:
#      - container-link
